version: v2beta1
name: superset
pipelines:
  dev:
    run: |-
      build_images --all
      create_deployments --all
      start_dev --all

images:
  superset:
    image: superset/superset
    context: .
    target: dev
    buildArgs:
      DEV_MODE: "true"
      INCLUDE_CHROMIUM: "false"
      INCLUDE_FIREFOX: "false"
      BUILD_TRANSLATIONS: "false"

deployments:
  superset:
    helm:
      chart:
        name: superset
        path: helm/superset
      values:
        extraEnv:
          DEV_MODE: "true"
          SUPERSET_SECRET_KEY: super-secret-key-1234

        configOverrides:
          default: |
            ENABLE_PROXY_FIX=True
            CSRF_ENABLED = False
            WTF_CSRF_ENABLED = False
            TALISMAN_ENABLED = False

        bootstrapScript: |
          #!/bin/bash
          export VIRTUAL_ENV=/app/.venv
          export PATH="$VIRTUAL_ENV/bin:$PATH"
          /app/.venv/bin/python -m ensurepip --default-pip
          /app/.venv/bin/python -m pip install psycopg2-binary

          if [ ! -f ~/bootstrap ]; then
            echo "Running Superset with uid {{ .Values.runAsUser }}" > ~/bootstrap;
          fi

        image:
          repository: ${runtime.images.superset.image}
          tag: ${runtime.images.superset.tag}

        init:
          enabled: true
        postgresql:
          auth:
            enablePostgresUser: true
          primary:
            persistence:
              size: 1Gi
            resourcesPreset: small
        redis:
          architecture: standalone
          master:
            persistence:
              enabled: false

dev:
  superset:
    labelSelector:
      app: superset
    sync:
    - path: ./superset/:/app/superset
    ports:
    - port: "8088"
    logs: {}

commands:
  prisma-db-push: |-
    pnpm prisma db push
    rm prisma/interfaces.ts
